apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runner-deployment
  namespace: actions-runner-system
spec:
  replicas: 5
  template:
    spec:
      repository: akshaykam/Self-hosted_Runner_OnEKS
